### ISSUE TITLE
consecutive underscores

### ISSUE THREAD

**Issue by chobbles** [SirWaddles/JohnWickParse#12]
When running the parser, it seems to drop everything that follows consecutive underscores.  e.g. I'm looking through an item database where most items show up as say ITM_078, ITM_079, &c, but others just show up as just ITM.  I suspect there should a number associated with it, but it seems to be just "ITM" (not sure how I can send the uexp and uasset files to reproduce this).

Is there a way to preserve consecutive underscores and the contents that follow?  

Thanks in advance!  Love the work.

**Comment by SirWaddles** [comment]
I'd need to see the files you're talking about. I've never experienced this issue. 

I can't think of any immediate reason why any code in the parser would strip underscores in any way, strings are usually represented as a length and a buffer, so they're not even null-terminated. The only parsing that goes on is to ensure UTF-8 compliance, (or in some cases, UTF-16, which then gets converted to UTF-8.)

My first thought is that that's just how the data is represented in the file. You can sort of try to confirm this using a hex editor. It could also be possible that whatever data you're after is being dropped by an unknown structure, which is not unheard of. If this were the case however, it's unusual that it would work at *all* in any case.

**Comment by chobbles** [comment]
[ItemDB.zip](https://github.com/SirWaddles/JohnWickParse/files/4231496/ItemDB.zip)

Thanks for the speedy reply.  

Please see attached for a sample uasset/uexp pair (hoping that works).  

After the ITM_037 entry, the next entry seems to be truncated to just ITM.  Based on "ItemID_117_6F1FA31F452C60041595208CCAED321E":56, I believe it should read ITM__116. 
 There are several instances of this occurring throughout the file when serialized, as well as with other files.

.

**Comment by SirWaddles** [comment]
I can't seem to find any indication that it's not being serialized properly. Any of the missing ITM_ values, such as (ITM_019) are simply not present in the name map (you can check this by hex editing the uasset file.)

**Comment by chobbles** [comment]
Thanks again for the reply.

There are a few items that don't exist; as you mentioned, ITM_019 is one of them (along with 021, 026, 027, to name a few).  The game appears to use two ID systems: one which is prefaced with ITM, and another which is the ItemID property, and ITM_001 is not necessarily ItemID: 1.

The parser correctly notes the ItemID of the items, but shows them only as ITM. For instance, ITM_037 (ItemID 55) you see:

      },
      "ITM_037":{
         "export_type":"RowStruct",
         "ItemID_117_6F1FA31F452C60041595208CCAED321E":55,
         "ItemNameID_118_78CF4DCD438E1C10ADEE2D951C83C0BE":"TX_NA_ITM_037",
         "DetailTextID_119_9EDA66264756DC5D79E5B2889F249818":"TX_CO_ITM_037",

while the next item entry is for ItemID 56, which should be ITM__116, but is identified as only ITM:
      "ITM":{
         "export_type":"RowStruct",
         "ItemID_117_6F1FA31F452C60041595208CCAED321E":56,
         "ItemNameID_118_78CF4DCD438E1C10ADEE2D951C83C0BE":"TX_NA_ITM",
         "DetailTextID_119_9EDA66264756DC5D79E5B2889F249818":"TX_CO_ITM",

There are a few others items with ItemID (about 188) where the ItemID is parsed correctly, but the ITM identifier (not sure if correct term) is not (e.g. ItemID 53 should be ITM__115, 103 should be ITM__117, &c, but they only show up as ITM.  The ItemIDs are correct though).

I can send the serialized file, but I'm not sure how to readily point to the exact locations.

**Comment by SirWaddles** [comment]
As far as I can tell, the file is being serialized properly. I was asking for an example of some data that was in the file itself, which you can view in a hex editor. The data that's "not there" in your case is not in the file.
