### ISSUE TITLE
Could not read MapProperty with types: ObjectProperty ObjectProperty

### ISSUE THREAD

**Issue by apocalyptech** [SirWaddles/JohnWickParse#17]
Hello!  This is from a serialization attempt on an object from Borderlands 3, not Fortnite, so feel free to chuck this in the bin.  I'm pretty sure it's technically a more generic situation than just BL3, though, even if it might not be showing up in Fortnite data at the moment.

Anyway, I've got an object which fails to serialize, with the following output:

```
Error: Property error occurred: 
Export type: OakCharacterSoundLogicComponent
Property Tag: CharacterSoundData (MapProperty) 56
Could not read MapProperty with types: ObjectProperty ObjectProperty
```

`OakCharacterSoundLogicComponent` is clearly a BL3-specific class type, but the error's getting thrown because `num_keys_to_remove` isn't zero, in this block: https://github.com/SirWaddles/JohnWickParse/blob/master/src/assets.rs#L1718-L1721

As a test, I tried doing a little loop from `0..num_keys_to_remove` in there, immediately after reading the value, calling this in each iteration:

    read_map_value(reader, key_type, "StructProperty", name_map, import_map)

... and it allowed JWP to produce a serialization for me.  Obviously this doesn't correctly process what it's being told to -- no idea what keys it's requesting be removed or whatever, but the serialization looks reasonable, and produces something at least.

Anyway, here's the files in question, if you're willing to take a peek:

https://apocalyptech.com/scratchpad/jwp/BPChar_PunkBadass.uasset
https://apocalyptech.com/scratchpad/jwp/BPChar_PunkBadass.uexp

... and the serialization once I put in my improper little hack there:

https://apocalyptech.com/scratchpad/jwp/BPChar_PunkBadass.json

Let me know if I can provide any more info!  And again, totally understandable if you don't want to deal with this, of course.  :)  Cheers!

**Comment by SirWaddles** [comment]
I still don't understand this. I think your solution is correct, but what possible use could there be to remove some keys from a map *before it's even loaded*?

My concern is that this entry somehow affected the contents of the array itself, and it never came up as an issue when loading files from Fortnite.

**Comment by apocalyptech** [comment]
Heh, yeah, it's a weird one.  I'm still not very familiar with how these things are laid out, so I'm not really sure what kind of keys it's saying to remove in the first place.  I *did* check the in-game property on the console (using the only useful console command BL3 lets us use, `getall`) and it looks like the serialization for that export *does* match what I got out of there.

Anyway, thanks for committing regardless!  Your tool's been invaluable in getting BL3 modding going.  :)
