### ISSUE TITLE
.uasset

### ISSUE THREAD

**Issue by ZhiYiDai** [SirWaddles/JohnWickParse#7]
How do I package .json back to .uasset?

**Comment by SirWaddles** [comment]
The conversion here is very much a destructive one. There is not enough data retained in the resulting json file to create the original asset data.

Generally speaking, my view is that the only reason you'd want to _create_ a uasset/uexp file is if you're actually working on a game. In which case you'd be using the Unreal Engine itself.

**Comment by ZhiYiDai** [comment]
Thank you. 
I want to localize the language of the game. I don't have the original uasset file. What should I do.

**Comment by Kein** [comment]
The only destructive part is the instance numbers that cannot be tracked properly unless you somehow manage to emulate/grasp whole eco system of the project. However, if you add a way to the user to be aware which FNames have instance numbers higher than 0 then in general it is safe.

**Comment by SirWaddles** [comment]
I'm not adding support for this. This is definitely a one-way conversion.
